name: NPM Publish

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
    - run: npm install -g @angular/cli@9.0.6 scss-bundle@3.0.2
    - run: npm install
    - run: npm run build:lib && scss-bundle
    - run: npm publish dist/ngx-picka-period
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
